
services: |
  - Observability:
      - Grafana:
          icon: grafana.png
          href: https://grafana.virtualthoughts.co.uk
          description: Grafana visualisation
          widget:
            type: grafana
            version: 2
            alerts: alertmanager
            url: https://grafana.virtualthoughts.co.uk
            username: {{HOMEPAGE_VAR_GRAFANA_USERNAME}}
            password: {{HOMEPAGE_VAR_GRAFANA_PASSWORD}}