apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: homepage-secrets
spec:
  encryptedData:
    GRAFANA_PASSWORD: AgAft28Qg6mk9BdojLVhDUr1pur+Jlje7VRcWrhTEmZZ0TdQhbMJAHp1qkCklraPN0RJes2Vdk6a8GgjIypzg+Bl+j0K/K6VGFidrJOPOXcBUA22ubif30eKdao+b8SG93hMZWxNB1yYSbHVy2VZhUi0U7pvqF7az16GH03SVf50zWp6Owr9staaY5+lrb/BypYpt23N8ojP5V+kO90s9fT1mgKHThAgaSmWY7SCkqkPiV+96rhVbkXZydlHBTPr2ypjT/8Zd+Hg8Edb+O9qOD6e5gja4nRIOsmCp9eYQ6y2eOHfhpEUgpZPa14bsBLshwp6hFK42PjKF5EjK/7OaGfhPcz9GGOCrr23MStx6JO9cj9xPg4QifUMwYVreJRgfrVFrQH1PkDJI9HCrt/v3F8Pij8DFmAFNK5gwOaNvD2TrEdPkuSgWDaBfZgQXJYa0qpj84eIKbAtfREY9nz+HkHagP0fcwXeqYV2k1PPebuIa/XbBD87Q+lJv4L1oDZI2chyc3MBQhr8oFZJOzx/fYo6wV2WPMEpwlsDgLs17CrTa/kzG5ZcMHy9mVM2tIsoxrWTXWbSV3v1fbFtwk4BWEaQpfr4x+qnD7mhHDRIupSgrqkbB/ORSO/NtLorXtTv5pMqL4cHDFNcL4HhuvKNrOmkOGSMBiPvEjgph2EmDE/QkyMYrdBoHzSNTuWTNNiL+YbzWN7aTwnE9mAYo/nq0O2HtXFQ7/UNUGn19J3tQelTApu4iytpwDhI
    GRAFANA_USERNAME: AgBvxrgdzNfthcxCw42HMxsPyvNyr2n/JtICGjhInm0qgL//6DC/OmiVMLTRiItSuW8Nz0UvH/IGtabQr/gqpjPc5xTJFgsmnH2xNyg7FhApDEWgo/83iy4Ymq5O7Sje14nOg8xuAK4ndYiRiQC2iJJGKKBlqRb94gmvKkaAzb8x7Rw0BCIKDFAK3SZS/5QIQkQhQSi98yvHLfrv6CjGN6a17iv7Z4ev3TNsCSnQttNd4p+vrNB8TcCsVuIc0aQ8HWsYhSKu7Q4LPISAKEL1tCvMrACEgEf0XgNlXEFIW4TpQ6sy102ztFFylh/z/xgB2AA0XY6dpSImpQ9O3qz10HRMBfqasmrRxuJtMz/N51HySnJD0Rcmk4SodOwQ/Qon5IDr/Tf1BJiVpr8/aHsugV60pis9JZd0FzbiJHOh3IpgpRdb4ewMPf6QQovX/9ijokH5YCVkviq1oaBdodqMLeS9FN8eEGjyEpsDhOYgOPGsNnsZ600JDurIF5Vmo1vCqMuv6fAG7ZkIHaOSdoiKyYmgNZxRsMbBZxeKkr4ULlrzCSDt18VWCUD3twU4fRjHPWvBZv9o5ryz+8fD5Ze3ese39h4CgEISUqTx5kUXHmxsfBXc3p9bWqvoxFLwkz6bxPoUGwDZs9ilKqKReHs1PIJVRsDsIIYdPEXS25cPPE6+aQ6f7c2kQG6lcwuRXaHkXZDkbUuyqw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: homepage-secrets
    type: Opaque
