apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: homepage-secrets
spec:
  encryptedData:
    GRAFANA_PASSWORD: AgCvVuXOIMSwjyGWb1zt0jXtzm8rJEYsCVF0KDJLHvohnbuO007jSHDAPsfmulxG3xzymkJmF7NuJddHv2l5HhwSLPoBTmGAJpCWQYrGw+eRd/0msT8789DESK7lFuei+5T6/bYySfGzFtr+ZHFZdeLY6whOuZR+VDpVXSfPz7jD5cj1BRdXoxs2cYg2wbGlcCtdmo8oCp5WXtGrZy6IDMfDHGqiY9ZIr5GGQqh1MWLluimgF30r4A2EiSmTT0LtTfdTZPVxeDP6NAnXafdM62ZrTWxE9wg+g4d1O+zGHYSdhW1KAUSgDaGjdZMXBw9b9AmjjveKNu24jUs244OQZTC3zaRE+Vf8dXg8AyQjJ52OHH8srPlRIEYcMcnYf9q1tHOYv1DlCFIcIUHnfRfYc32N6BF2hKmp+V3Eh/q8nCZnQY6VpoqDI8rQD6rfDcCv5fekzF7BXmVIHFu/kKCxm4g51zovWlgr/mYJxU1vNf6QeNu9mBhtH1vIb6vcS6t5z4oThySUxIf54jkoPcbH+rpLWmXNL0dn1ZaGuWOC9qAqU4L5wxz46NixqeAQ4umFKglEFrHwun3D9uce4hMlcp01dhRUQacf9iF9yzJ6q0PveTI51jCHaCsw4ZKCfb6F703+xUgqeIxdSSybYnYHdkLRh2IMRMwnKYP9crMOZxrEUSJcal+f9Ewjy16qQr9/cQ3vA0xOsg5BDTYtoSOs5+KFjUYKGa7xuobhJa1KeyNAFEjUks9eFtlV
    GRAFANA_USERNAME: AgB3rFStEGKsEWJSxcqimgH8C+s+N9ZDewLOEzD74hZlxyCysRjbC1a+/DMP1Hy3YlUZCADBLX7rrvyqEpzwWz6I4PIsgyspel2ZxuGB+wUKG29NPoouvPl6aoo7OKyb1UiJMwDnxx3KYVD/uNhnvbYLgaCvi4TFzAZ+lDoVF4erGQ7PrVHgV4TwoT2MuFjcsm9gHMdvnJ7JkG9qe5tng9dyhHXwrd/s6k8DZSp3wwPCfk4iAbFLnstlMoA4awxXsWr0J5/fANkAwWGSI/NkIMPyTsQt8r6u5PcmAp9rSyea5Teeb7Nys4qplDUuTwQSK02i3aFu3fLxN/++tUG4f2KkbFCkg1ywXtb9Z2I74ysEsFAWbY/ohBI8WQ31BUusMzEv8lbpEqjsG+cxvjR/u71vMHEGVD3HCaxzocSf9SvnQpdiJ6xflACwi9UGNE8AdDwlpJyBnLF+/4Wuh2SQ6j80Zy9mQbMlC4c/PnJk0nvTMsBqz53alnp4J7bJfG/WDktP+gjBnDZ4idN3kbZaxRypwnM+pY1F0YrtlA3nJetRU1EtUQyGAkYqg52XigLl7mPvq7yx93xPgd39ItS3rcEWYZCnKKS1xe6iosNDtcJviVnEunXBHeJs1k1qoYHRQbaU66yYAmmKAjMkJEY8HdDA4oqgyzH5U/8bflz+gpQGm0fjG2rPJnIZRt6JymTZzoFS2J01rA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: homepage-secrets
    type: Opaque
