apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: homepage-secrets
spec:
  encryptedData:
    GRAFANA_PASSWORD: AgCKw4T3qQ95qVgRY3WiJ1T2U6gfN5+UBGkmt8rTwMykF3u2LIAuvD+Am6eoPk3fFyzGRCDTO4OaejNa3ET2sm0Ki5uvYS1oc209rMNZC4bbRdvIDc0386X3lK6IrVmFKHIX1+IleOuIHWHXjDt7NWWVYzNJzTwwdYlzTlbxyhSLzfybgbL8nH76G50LeyzsbVt1aTLHsJ17mWyJT/ziHOUd7Bfa8XOtXYaKTyA+gLMqQQynfZq7cgkuZDMQq7U8tuVUMwwxGcp3fyLn/47I+aPADDwEj/41q2XanVYaq+iNHQuogX4lLE84uA9OTqFLbgvRbBcLpoz6nNESA+BrM292v1V7MOirM6S39lj/T0ebxRi2ntynHoAvyuUlerLktV8dnUPohD8eUQUmuL5lCx7vQIEB4unpL284HLvL6QtMl0D20UE6Au5Ov60mQQ57QFP2x2dT/wpqBRIIdwzA1mcAEazCoi3G00Ak4moboeKn6T6P8fyJCsK8/z1su3umrkjw3NtWj6GVR/Yn2EYwyrRPbSWm4dLf4xFS2fvD/j8YjbICk+Dkc0dgKVTsS+7ahOLzlmaO7Dcgc2f7G2C8/ItCl8iOXCFt2GDTZLflPSiL/jLZu3rQ1o2u1Y5bVQbW5xWT/9qZI6XOH2s9cI0Lk3u4a+4cnhn6aQF8QHKoYcKV442IzjPrOmctFqRcA4eVZ88tYldHirOXz2Q5IGKTATU38aW60OB3J5DONcVyTeHpvZ2SG5T6C7uQ
    GRAFANA_USERNAME: AgCvnXmiNNG6cyPgXlj1oCBX7luX4Lbwn+ypdvCfnwF/LgdsgYY1OMBqpYd/UqpoivbQEFs3YxY0XJN4HprDVUdpzt1GxBU+ORxAaPJf2dzsiJlhp2j8N9UvKn037wBG2rJmTzBKmF+XDtMdoO0vDGxYMZGPQuMztaEH04Lz8z7TOSOcvtxto2dE6Ah2e61MkbRVItLzEHF2VmU0QewzG4ZzgqDPOtk2jNVDsWhxo/IL10EfRFs/Ue56XiTsdlAkubAIx0kn2dM46ABtn+2+wn8aeKjquneA/jyjxZtKXTzlR0Wol0RNlprYrc+iZlKGHluoxwtl7ifoxdhFCON8tFh33p7sjrkP5JzUqexWrgIhbUDSFj0W/ipeomF/fNRwZiuktd4L0K3FxHhG1tr7PBYUgPRPUCyTv+kt6zcxethTLhegxSD9ssEcKD0nBohTLSFFuym/HlfrTzAppSPdsfYFOB9+vlAbAXJOlIKR26dqpyuHgvQcteL9d1xHxC/TtH+Vmz7v2y+O7578jE1e3XG/X3g8gnKP8SCYJv5lWCr5TXkYzUV1XO12ADwTT2vUO4/zZFRy4FFoszowjHGirSskgYkbl34dfQ0wHU3/l87ScF9DmjxkJYqOhxriYkBHK9WyJlY6BGrEc0wc8t/s6xeh9x2itgPoe0lV77L5S4kUIHxc3VkS9BFRP9itctaKeSoVGY1HCA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: homepage-secrets
    type: Opaque
