apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: homepage-secrets
spec:
  encryptedData:
    GRAFANA_PASSWORD: AgBIkWDGCw6ytbtaKoNGVtcX0u8hLXFoLFUZGKRYu8RyJmR43QqE1Z6AjACtDjONadYBqV6VgVxrdaRajngJwqhFzYuyhBTc9YjiVqxTaVkO5V+gD7WUYcMb+CIG+SQBHCltQfidTLEWJQQjIDgS640/mrmmmIxbbFATV+YrXi9JS63Byb60Pvo+ta8VqzkeA9vwZULsmUmq5R40VTU3oelXgLWly5+XPHXC0ph6ZL79c6T5hyXyuE/0JOD8qFYg8aWsSNirQ1QIU8V5e5LrYkw7Ksyy6XH8Z2PqvyxHshwZSRy50ns8QG7icjPYV7wrWYxnzAMCLCp9elkKQpeSaTJ3/SRYPS/VWxukknuydln4sHSR94iPYCk+FFbRpAqPfc1Di+wLws+IW2sc5jovlDpk/o2ZI/xfhG+GM0562kpxrB8qNk9F3DDyA/yE0ofpNbDIT46mrBk7li2cp87dP0pn+7eYd5fafnJO3oo5Wik82L3IytZJ7aXD9g9/tTFaEG5jabTIzZkn4gN6HpNAjsXUQLi4g0TJYGMcTotnhU0d2VH6r5gka46LzhyEwcaY3lkNXKQ+1BPLMO76/vJ9BJ4PoPjUNnJfWPSXoquyLKj6f9ifzIymrEegU4mziCkRHZtxMj6blIw/nx0KguNEdyouODFRtOhSV+nsu79rPnGe7BAsl78HOBTyVSzfkIpECS8CbywHPWmnarwA8fClOj28l3kBAgphfC0SLJJWIjpmiD1WgbB84+x8
    GRAFANA_USERNAME: AgAw1cw3QnGKfppIYxDO3SKWk2wlP12mlRHtdllxfekHG15Tj9ShG5f4QAbWooxoGKid1f2kthir27mIpUZmK2Qubgi1hQ4j/qgtoWy+HJdIrHCNqBZbf4YgffVGhjcBp0W4koXWDoEEQmX6BM0hAkkcDYEWK91rRGv5ac5+fwW0SoALUHqEwmoMwaJ8pVfA8aIVLsTcVwLnE+LjwjXZMpmu8IOTHz3if6Fxu/7Jy8Mkg6LpjvUqT22vLnPEWLFaO5/09YQIHEBRpU6m/M0Z5hBQFBfe2kqbF/pkdHrz9m0a4xna8LEwQcYG7CZESAH2NTdsinx/DhV6zDNY5zE/iqSBu8wdJZmvWjASabSOF4VltN60V9NvRZfIL5h+9rXls+l5wwmkHyNUJ72jaaKVTiCysz4I4hv3UwiMyTzTag4xhw5u8AdWAc5wKNu8qvGdOiwvZctigwW1fGyodMqXhTWconvO92dwVQ5bhPan6B+nuP+dX2kamDqq09tWjg/fx+r6ituX1MruvTPLspMRlTfvE+TTtVWSwJt7uC5T2KnZvE/ZEoAVs/SDUAhWCQM5b/brbf48Rc3h2Wr4LAfWER7tfVF2T/rr4FJ5RXKTxUCp3g04tXl/doA4xMhBaMspbZwz1Zl1qfuB4URV/qDdLtcriv8TyIfWdSwRIau643RjFKLZMFbiqF/3KgBnqNUcSG8SJeL+6g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: homepage-secrets
    type: Opaque
