apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: homepage-secrets
spec:
  encryptedData:
    GRAFANA_PASSWORD: AgCueRUiAkKJXfaLYrMMzHxhMKd/330aPIg4o4RbqJVtFnw/oR3a+W83EWa/GIhdeNu2j7sfjjSr24yv4N2Yb01gDKar2NXnDAd6LQystCuH58d9MdgSPrsTdNyJnudzbRNtHrUOdynMzyzwcQ5IdOSNLpD/kBAQdMQfm7dcEN4COr6yHWFW0186ar5+fO2LobkEjTIyelffGM4QOBOoNBPMxngyGKOu8rMRALHgjxW+CuJoxd7+4g0fpmXC0sHVK14bJDlPdmj8qZjCzwcX2z6OU+dfQ4yHBr2x3fCFU5v5TspF8a5wKsbZL/87TlTenxlT3ksoawvGEdJGO40AFxiDp4EkGPomlToSiJsa4hFY7TF+xFVmwzIy0dibQXnqyJJEAhwMmgIAqINCLh/A2JO3gQU03bc5EWEZszE/PHF3Q5lEogHg4pvgVibSDI3bF/94WxHBgmdV9Xf3vkkPqC+zLq9YMN47giNGxNzumHdTnEqgDn23aaeuTLJ/wkMeCJT95rAsnk2jz+skM9GEfhWjiP1Zs5+6UGYlmOvSZgFTHulH15zb78vpPH836hdZmnL/IQdZ560RPob7giJA+Kg0b3u+c9kHQ+ZHlP6Xz0fuZFTN286WxGGZn0xk6kOl0opiTnwjRmSZVImdVYusf0/EUV6oSFQzbPxUgsttGrKIMKG6IBMirfxGqNzjWAsMBsNNybJ+KsbNZ95atezjufvHzwo4gPJ9+ORDp18wwi0=
    GRAFANA_USERNAME: AgA9Wxnmz1bpFmNOwQ4MNz7FssQVMKr5vwdYc0BxzID3Pam0/h3aaqQ5ICNaVr6St+Dyu1zNjXKOjms004CVC+rD/W5Gi4fm+6XwLdAQdFJwyjRkZFNkER6c8/kBse/5KXppfshC+Yx4PnP8nIHf2CAYpakW3P67BswC1cjNKfrBRlwG9zka6GyS0SNyp0aCqxtEBplxSQf6tuR6r6KPg5sDcwjjRdpB3pJcjxhVzhZsSOCMnOsPvicZtksAWyJ19f5R71rFzdEPd/BcSTGsOfoUyQxjkH22FRaYgHgrkIu4K/ddYgkpl87JqwPYtcY3Lpr9x0NyMOZ9gTh4pAz3JQelV7ng7ohcEX7KstcL63KjsOJIHQBdSkYL8TNXO/Xa8mwIzgRs9PBG/aCDrB+lggFdCc4WQdZNXW/p1txRf1eON7XbRaaFBgdBgjnO5FYwvj/fC9NLtMT3RKCMrw9ck0q5voxcOMC288uqoTAjWL3DlHRiYfg0Qcd/Bhiwfth3ydzA4CxA6Mf2nOuZadXSe9OKBQdxAMe72BJRM+PGHadE6zL6UshY2jwjKB3FXUREjjxCDhfTZPtau2qRQISb/BBrEytGE4ckpDt4yI1/apHcQ6NVI7WuxtHEmwKBHXzQnEW50YUscukGu9wVKO5Z1TEVsCfoj6r0JZmjnGe+R+jLyNuFR6CK9JZLyCLmZ4We1PXRc5fPbQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: homepage-secrets
    type: Opaque
