apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: homepage
spec:
  hostnames:
    - "homepage.virtualthoughts.co.uk"
  parentRefs:
    - name: cilium-api-gateway
      namespace: cilium
      sectionName: https-gateway
  rules:
    - backendRefs:
        - name: "homepage"
          port: 3000
