apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: grafana-credentials
spec:
  encryptedData:
    GRAFANA_PASSWORD: AgAOnFtAtSSGY7yDKaeiJjkJXSoepGDKtB9VWrVLrSJPio6utsMglQprRsYzgCJuvvISJxNAuBBMJiRP5CfeXtbFv8rP5oRHQZCvqLAdoOHeMiy1P8hgaIAe3lWLSYfHUETlwhT3vDgRhhM4eOb+w+xwWUvd2KYtKyPlZfnEqp9Thbs2RZtAC64lT0X0M0F1ghTXvBnVA/P9pdOcYGmPTfR8MJtuXFK70tdlQbJ8yKD8u2ODk9F+T+Q3QHOfLiJyrezdgL/ZkhVexo5VNCWr0T1utznire2MdohfIh5ldWSS+q5Wl8w/LCdIOtxpqTIhVG3/++WhRtx2nnjrNy5s0hvPukwI+VhgKq3dYH0lXl4v7yo3ZWt6FENTfvihF3qDaMY4XbN6r5PDKUjsE3yLOcSqT21daxKRnM8yG+ZwnRnkipeb2/D+OpjoaUopP5EM31pufx/PhuSAHtZa7u9zE2D2/apmkpoUuvTvChc3xwnvmtnHeTcaWqdI63p7AgeoK6KqYuKaHr9z6wuyqSa+b9a3ky6WsZ5ku67yejlk0q1soViXWleIoFn4mj39MhiHzpy1fhhW7VmFyXHaJm8JEOuDcHVyXesNiy5dhkofRwvcaM11OEY8UBNPLKXQF7CqRPXpjHIrVhFeFxk2KZr593ghwyB3bh5jwJp1o1NRULoD3NnfUJnFu2UMyCsCX4yZ/EP63MMwe/9F9YR14cItcvpXmyoL05zmupG4vWT2bGDAyzXT0bDLwmks
    GRAFANA_USERNAME: AgBjA6cwp7Jwa0DXBvV4daWIXbgk1rk/C7YOLdrxVdOoQDQitJiiWlwBCq9kJPWqqZtbVVoX+o3V6NXFzoKqtayN4povSB/Glx9ifaXiYyBCw7oUfeINDUmfCQDgvU10ax2UFSbrudJFKyREZd3B6NPub6whQGAWLhO2DxM8G3oPa8O8xZdWXAS46uL/eK5JNt0X/XfxzHHU13E13YY9+tKYV61bOYbfKnDLUgPApBFGLMMSZV6BzUMAKba1qOkuTD6+fXMQ/1mz9Cksa3zD/QueiL6DuRBE8aOq8Vl2OzOBRNYWAUz9FFPgdaAL1pprkS7aXfNIwRPQm7wm1y11pbZzR0CETZF9sI7Xb1la1wwWw2GnsqwthL5GzA599d2w0Npp0yaFGq1wsOl/cY7v/3TDZkJ9mTAOxuubE2Gj8v43otMjRXyCp+PGqBlu4c4eAXT4/+Cb8RJvQid8HY9MS9QNRkZs+LXCpVLhrtKXRrxZkVTNzjcmanZercMTg/K++ZKhRlER2Rm519NHFNqWPLJdiaOh9maf+fjULawnSm1P+S7WAysw1r4mB1QMPMVFTcnWZ+hOx+v43te6545S4vSQ/NXeJm0BVB239OP/l0b2lZ1uXsmF5xn+jq1BrF5sSmmINxJkBrNKNDRJxo37aJTOp0hC9y6nzjQK4Ku0x00Z1V7nfngf1izj1L7cxM4eJL75B1+D7g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: grafana-credentials
    type: Opaque
