apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana-route
  namespace: kube-prometheus-stack
spec:
  hostnames:
    - "grafana.virtualthoughts.co.uk"
  parentRefs:
    - name: cilium-api-gateway
      namespace: cilium
      sectionName: https-gateway
  rules:
    - backendRefs:
        - name: "kube-prometheus-stack-grafana"
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prometheus-route
  namespace: kube-prometheus-stack
spec:
  hostnames:
    - "prometheus.virtualthoughts.co.uk"
  parentRefs:
    - name: cilium-api-gateway
      namespace: cilium
      sectionName: https-gateway
  rules:
    - backendRefs:
        - name: "kube-prometheus-stack-prometheus"
          port: 9090
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: alertmanager-route
  namespace: kube-prometheus-stack
spec:
  hostnames:
    - "alertmanager.virtualthoughts.co.uk"
  parentRefs:
    - name: cilium-api-gateway
      namespace: cilium
      sectionName: https-gateway
  rules:
    - backendRefs:
        - name: "kube-prometheus-stack-alertmanager"
          port: 9093