apiVersion: v1
kind: Service
metadata:
  name: mktxp-exporter
  labels:
     app: mktxp-exporter
spec:
  selector:
    app: mktxp-exporter
  ports:
  - name: http-metrics
    port: 49090
    targetPort: 49090